<section class="mx-auto max-w-2xl px-4">
    <div class=" mx-auto mt-5 rounded-2xl max-w-xl shadow-sm bg-white text-light-bronze-800 ring-1 ring-light-bronze-200">
        <div class=" rounded-t-2xl py-2 bg-linear-to-r  from-orange-50 to-papaya-whip-100 border-b-2 border-light-bronze-200 ">
            <p class =" mx-auto py-5 px-5 font-semibold text-xl text-tea-green-900">Task Created Successfully!</p>
        </div>
        <div class="mx-auto max-w-md">
                <div class="mx-auto flex justify-center items-center gap-4 py-4 pt-6">
                    <label class=" text-lg text-light-bronze-900 font-medium pl-1">Title:</label>
                    <input class=" flex-1 px-4 shadow-md ring-2  ring-light-bronze-200 rounded-sm" type="text" id="title" name="title">
                </div>
                <div class="mx-auto flex justify-center items-center gap-5 py-4">
                    <a href="<?= $this->baseUrl() ?>/task/list" class=" pr-0">Cancel</a>
                </div>
        </div>
    </div>
</section>