<section class="mx-auto max-w-2xl px-4">
    <div class="mx-auto max-w-xl rounded-2xl py-2 mt-10 bg-linear-to-r  from-amber-50/50 to-amber-100/50 border border-amber-200 ">
        <p class =" py-5 px-5 font-semibold text-xl text-amber-600">Create New Task</p>
    </div>
    <div class=" mx-auto mt-3 rounded-2xl max-w-xl shadow-sm bg-white/40 text-amber-800 ring-1 ring-amber-200">
        <div class="mx-auto max-w-md">
            <form action="<?= $this->baseUrl() ?>/task/create" method="POST" class="mx-auto max-w-md ">
                <div class="mx-auto flex justify-center items-center gap-4 py-4 pt-6">
                    <label class=" text-lg text-amber-600 font-medium pl-1">Title:</label>
                    <input class=" flex-1 px-4 shadow-md ring-2  ring-amber-200 rounded-sm" type="text" id="title" name="title">
                </div>
                <div class="mx-auto flex justify-center items-center gap-5 py-4">
                    <a href="<?= $this->baseUrl() ?>/task/list" class=" pr-0">Cancel</a>
                    <button type="submit" class=" cursor-pointer bg-amber-50 ring-1 ring-amber-100  text-amber-600 text-base font-semibold tracking-tight shadow-md py-1 px-2 rounded-md ">Create</button>
                </div>
        </div>
    </div>
</section>